export const users = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@therapath.com',
    password: 'admin123',
    role: 'admin',
    phone: '+63 912 345 6789',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'Juan Dela Cruz',
    email: 'juan@example.com',
    password: 'user123',
    role: 'user',
    phone: '+63 912 345 6790',
    address: 'Brgy. Sta. Ana, Taytay, Rizal',
    dateOfBirth: '1995-05-15',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 3,
    name: 'Maria Santos',
    email: 'maria@example.com',
    password: 'user123',
    role: 'user',
    phone: '+63 912 345 6791',
    address: 'Brgy. Dolores, Taytay, Rizal',
    dateOfBirth: '1998-08-22',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 4,
    name: 'Pedro Reyes',
    email: 'pedro@example.com',
    password: 'user123',
    role: 'user',
    phone: '+63 912 345 6792',
    address: 'Brgy. San Isidro, Taytay, Rizal',
    dateOfBirth: '1992-11-30',
    createdAt: '2024-02-10T00:00:00Z',
  },
]

export const appointments = [
  {
    id: 1,
    userId: 2,
    userName: 'Juan Dela Cruz',
    userEmail: 'juan@example.com',
    userPhone: '+63 912 345 6790',
    date: '2024-03-25',
    time: '10:00 AM',
    type: 'Academic Counseling',
    status: 'confirmed',
    notes: 'Need guidance on course selection for next semester',
    isAnonymous: false,
    createdAt: '2024-03-15T10:30:00Z',
  },
  {
    id: 2,
    userId: 3,
    userName: 'Maria Santos',
    userEmail: 'maria@example.com',
    userPhone: '+63 912 345 6791',
    date: '2024-03-26',
    time: '02:00 PM',
    type: 'Career Counseling',
    status: 'pending',
    notes: 'Exploring career options after graduation',
    isAnonymous: false,
    createdAt: '2024-03-16T14:20:00Z',
  },
  {
    id: 3,
    userId: null,
    userName: 'Anonymous',
    userEmail: 'anonymous@therapath.com',
    userPhone: 'N/A',
    date: '2024-03-27',
    time: '11:00 AM',
    type: 'Personal Counseling',
    status: 'confirmed',
    notes: 'Prefer to remain anonymous',
    isAnonymous: true,
    createdAt: '2024-03-17T09:15:00Z',
  },
  {
    id: 4,
    userId: 4,
    userName: 'Pedro Reyes',
    userEmail: 'pedro@example.com',
    userPhone: '+63 912 345 6792',
    date: '2024-03-28',
    time: '03:00 PM',
    type: 'Academic Counseling',
    status: 'completed',
    notes: 'Follow-up on previous session',
    isAnonymous: false,
    createdAt: '2024-03-10T11:45:00Z',
  },
  {
    id: 5,
    userId: 2,
    userName: 'Juan Dela Cruz',
    userEmail: 'juan@example.com',
    userPhone: '+63 912 345 6790',
    date: '2024-03-29',
    time: '09:00 AM',
    type: 'Career Counseling',
    status: 'cancelled',
    notes: 'Had to reschedule due to conflict',
    isAnonymous: false,
    createdAt: '2024-03-18T16:30:00Z',
  },
]

export const timeSlots = [
  '09:00 AM',
  '10:00 AM',
  '11:00 AM',
  '01:00 PM',
  '02:00 PM',
  '03:00 PM',
  '04:00 PM',
]

export const appointmentTypes = [
  'Academic Counseling',
  'Career Counseling',
  'Personal Counseling',
  'Group Counseling',
  'Crisis Intervention',
]

export const clientRecords = [
  {
    id: 1,
    clientId: 2,
    clientName: 'Juan Dela Cruz',
    sessionDate: '2024-03-20',
    sessionType: 'Academic Counseling',
    duration: '45 minutes',
    counselor: 'Dr. Maria Santos',
    notes: 'Student is struggling with time management. Discussed strategies for prioritizing tasks and creating a study schedule. Recommended follow-up in 2 weeks.',
    followUpRequired: true,
    followUpDate: '2024-04-03',
    status: 'active',
    createdAt: '2024-03-20T10:45:00Z',
  },
  {
    id: 2,
    clientId: 3,
    clientName: 'Maria Santos',
    sessionDate: '2024-03-18',
    sessionType: 'Career Counseling',
    duration: '60 minutes',
    counselor: 'Dr. Jose Reyes',
    notes: 'Explored career interests and aptitudes. Administered career assessment test. Student shows strong interest in healthcare field. Discussed various career paths in medicine and allied health.',
    followUpRequired: true,
    followUpDate: '2024-04-01',
    status: 'active',
    createdAt: '2024-03-18T14:30:00Z',
  },
  {
    id: 3,
    clientId: 4,
    clientName: 'Pedro Reyes',
    sessionDate: '2024-03-15',
    sessionType: 'Personal Counseling',
    duration: '50 minutes',
    counselor: 'Dr. Ana Mendoza',
    notes: 'Client discussed stress management techniques. Experiencing anxiety related to academic performance. Taught breathing exercises and mindfulness practices. Progress noted from previous session.',
    followUpRequired: false,
    followUpDate: null,
    status: 'completed',
    createdAt: '2024-03-15T11:20:00Z',
  },
  {
    id: 4,
    clientId: 2,
    clientName: 'Juan Dela Cruz',
    sessionDate: '2024-02-28',
    sessionType: 'Academic Counseling',
    duration: '45 minutes',
    counselor: 'Dr. Maria Santos',
    notes: 'Initial consultation regarding course selection. Reviewed academic goals and degree requirements. Provided guidance on elective choices aligned with career interests.',
    followUpRequired: true,
    followUpDate: '2024-03-20',
    status: 'completed',
    createdAt: '2024-02-28T10:15:00Z',
  },
]

export const announcements = [
  {
    id: 1,
    title: 'New Counseling Hours',
    content: 'Starting next week, we will be extending our counseling hours. We will now be available Monday through Friday from 8:00 AM to 6:00 PM, and Saturdays from 9:00 AM to 2:00 PM.',
    category: 'Schedule',
    priority: 'high',
    isActive: true,
    createdBy: 'Admin User',
    createdAt: '2024-03-20T09:00:00Z',
    expiresAt: '2024-04-20T09:00:00Z',
  },
  {
    id: 2,
    title: 'Mental Health Awareness Week',
    content: 'Join us for Mental Health Awareness Week from April 1-5. We will be hosting workshops, seminars, and group counseling sessions. All students are encouraged to participate.',
    category: 'Event',
    priority: 'high',
    isActive: true,
    createdBy: 'Admin User',
    createdAt: '2024-03-18T14:30:00Z',
    expiresAt: '2024-04-05T23:59:00Z',
  },
  {
    id: 3,
    title: 'Career Fair Preparation Sessions',
    content: 'Free career counseling sessions available for students preparing for the upcoming career fair. Learn how to create an impressive resume, practice interview skills, and network effectively.',
    category: 'Career',
    priority: 'medium',
    isActive: true,
    createdBy: 'Admin User',
    createdAt: '2024-03-15T11:00:00Z',
    expiresAt: '2024-04-15T23:59:00Z',
  },
  {
    id: 4,
    title: 'Anonymous Counseling Service',
    content: 'We now offer anonymous counseling appointments for students who prefer confidentiality. You can book appointments without providing personal information.',
    category: 'Service',
    priority: 'medium',
    isActive: true,
    createdBy: 'Admin User',
    createdAt: '2024-03-10T10:00:00Z',
    expiresAt: '2024-12-31T23:59:00Z',
  },
  {
    id: 5,
    title: 'Holiday Closure Notice',
    content: 'The counseling center will be closed on March 30th for the holiday. Emergency services will still be available through our hotline.',
    category: 'Schedule',
    priority: 'low',
    isActive: false,
    createdBy: 'Admin User',
    createdAt: '2024-03-01T09:00:00Z',
    expiresAt: '2024-03-30T23:59:00Z',
  },
]

export const inquiries = [
  {
    id: 1,
    name: 'Sarah Anderson',
    email: 'sarah@example.com',
    phone: '+63 912 345 6793',
    subject: 'Group Counseling Sessions',
    message: 'I would like to know more about the group counseling sessions. What topics are covered and how can I join?',
    status: 'pending',
    createdAt: '2024-03-19T15:30:00Z',
  },
  {
    id: 2,
    name: 'David Martinez',
    email: 'david@example.com',
    phone: '+63 912 345 6794',
    subject: 'Career Assessment',
    message: 'Can I schedule a career assessment test? I am unsure about my career path and need professional guidance.',
    status: 'responded',
    response: 'Thank you for your inquiry. You can schedule a career assessment through our booking system. Please select "Career Counseling" as the appointment type.',
    respondedAt: '2024-03-19T16:45:00Z',
    createdAt: '2024-03-19T14:20:00Z',
  },
  {
    id: 3,
    name: 'Anonymous',
    email: 'anonymous@example.com',
    phone: 'N/A',
    subject: 'Confidentiality Question',
    message: 'How confidential are the counseling sessions? Will my information be shared with anyone?',
    status: 'pending',
    createdAt: '2024-03-20T10:15:00Z',
  },
]

export const dashboardStats = {
  user: {
    totalAppointments: 3,
    upcomingAppointments: 2,
    completedSessions: 1,
    pendingRequests: 1,
  },
  admin: {
    totalAppointments: 5,
    pendingAppointments: 1,
    confirmedAppointments: 2,
    completedAppointments: 1,
    totalClients: 4,
    activeRecords: 3,
    totalInquiries: 3,
    pendingInquiries: 2,
  },
}

export const appointmentChartData = [
  { month: 'Jan', appointments: 12 },
  { month: 'Feb', appointments: 19 },
  { month: 'Mar', appointments: 15 },
  { month: 'Apr', appointments: 22 },
  { month: 'May', appointments: 18 },
  { month: 'Jun', appointments: 25 },
]

export const appointmentTypeData = [
  { name: 'Academic', value: 35 },
  { name: 'Career', value: 28 },
  { name: 'Personal', value: 22 },
  { name: 'Group', value: 10 },
  { name: 'Crisis', value: 5 },
]

export const notifications = [
  {
    id: 1,
    userId: 2,
    type: 'appointment_confirmed',
    title: 'Appointment Confirmed',
    message: 'Your appointment on March 25, 2024 at 10:00 AM has been confirmed.',
    read: false,
    createdAt: '2024-03-20T09:30:00Z',
  },
  {
    id: 2,
    userId: 2,
    type: 'appointment_reminder',
    title: 'Appointment Reminder',
    message: 'You have an appointment tomorrow at 10:00 AM. Please arrive 10 minutes early.',
    read: false,
    createdAt: '2024-03-24T08:00:00Z',
  },
  {
    id: 3,
    userId: 3,
    type: 'appointment_cancelled',
    title: 'Appointment Cancelled',
    message: 'Your appointment on March 29, 2024 has been cancelled. Please reschedule.',
    read: true,
    createdAt: '2024-03-18T16:45:00Z',
  },
  {
    id: 4,
    userId: 2,
    type: 'announcement',
    title: 'New Announcement',
    message: 'Mental Health Awareness Week is coming up. Check announcements for details.',
    read: false,
    createdAt: '2024-03-18T14:35:00Z',
  },
]

export const announcementsFeed = [
  {
    id: 1,
    title: 'Barangay Mental Health Program Launch',
    content: 'Brgy. Sta. Ana is launching a free mental health screening program for all residents. Schedule your appointment today.',
    category: 'Community',
    date: '2024-03-22',
    author: 'Barangay Health Office',
  },
  {
    id: 2,
    title: 'School Counseling Workshop',
    content: 'Taytay National High School invites parents and students to a workshop on managing academic stress. March 30, 2024 at 2:00 PM.',
    category: 'Education',
    date: '2024-03-20',
    author: 'TNHS Guidance Office',
  },
  {
    id: 3,
    title: 'Mental Health Awareness Month',
    content: 'April is Mental Health Awareness Month. Join our community activities and learn about mental wellness.',
    category: 'Health',
    date: '2024-03-25',
    author: 'DOH Rizal',
  },
]

export const dailyTips = [
  'Ang pag-asa ay laging nandito. Huwag matakot humingi ng tulong.',
  'Mahalaga ang iyong kalusugan. Alagaan ang iyong sarili.',
  'Huwag mag-atubiling makipag-usap sa isang kaibigan o counselor.',
  'Ang pag-aalaga sa mental health ay hindi kahinaan, ito ay kalakasan.',
  'Magtiwala sa proseso. Ang pagbabago ay nangangailangan ng panahon.',
  'Ikaw ay hindi nag-iisa. Maraming tao ang handang tumulong.',
  'Maglaan ng oras para sa iyong sarili. Self-care ay importante.',
  'Ang bawat araw ay bagong simula. Magtiwala sa iyong kakayahan.',
]

export const counselorRoster = [
  {
    id: 1,
    name: 'Dr. Maria Santos',
    specialization: 'Clinical Psychology',
    credentials: 'Licensed Psychologist - PRC',
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableTimes: ['09:00 AM - 12:00 PM', '02:00 PM - 05:00 PM'],
    contact: '+63 912 345 6800',
    email: 'maria.santos@therapath.com',
    image: 'https://i.pravatar.cc/300?img=32',
  },
  {
    id: 2,
    name: 'Dr. Jose Reyes',
    specialization: 'Family Therapy',
    credentials: 'Registered Guidance Counselor - PRC',
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    availableTimes: ['10:00 AM - 01:00 PM', '03:00 PM - 06:00 PM'],
    contact: '+63 912 345 6801',
    email: 'jose.reyes@therapath.com',
    image: 'https://i.pravatar.cc/300?img=46',
  },
  {
    id: 3,
    name: 'Dr. Ana Mendoza',
    specialization: 'Child Counseling',
    credentials: 'Licensed Psychologist - PRC',
    availableDays: ['Monday', 'Tuesday', 'Thursday'],
    availableTimes: ['08:00 AM - 11:00 AM', '01:00 PM - 04:00 PM'],
    contact: '+63 912 345 6802',
    email: 'ana.mendoza@therapath.com',
    image: 'https://i.pravatar.cc/300?img=47',
  },
]

export const barangayData = [
  {
    id: 1,
    name: 'Brgy. Sta. Ana',
    studentCount: 450,
    commonConcerns: ['Academic Stress', 'Family Issues', 'Career Guidance'],
    coordinates: { lat: 14.5673, lng: 121.1327 },
  },
  {
    id: 2,
    name: 'Brgy. Dolores',
    studentCount: 380,
    commonConcerns: ['Mental Health', 'Peer Pressure', 'Self-esteem'],
    coordinates: { lat: 14.5712, lng: 121.1289 },
  },
  {
    id: 3,
    name: 'Brgy. San Isidro',
    studentCount: 320,
    commonConcerns: ['Academic Performance', 'Social Anxiety', 'Career Planning'],
    coordinates: { lat: 14.5645, lng: 121.1356 },
  },
  {
    id: 4,
    name: 'Brgy. San Juan',
    studentCount: 290,
    commonConcerns: ['Family Conflict', 'Depression', 'Academic Guidance'],
    coordinates: { lat: 14.5698, lng: 121.1312 },
  },
]

export const followUpReminders = [
  {
    id: 1,
    clientId: 2,
    clientName: 'Juan Dela Cruz',
    lastSessionDate: '2024-03-20',
    followUpDate: '2024-04-03',
    priority: 'high',
    counselor: 'Dr. Maria Santos',
    concern: 'Time Management Issues',
  },
  {
    id: 2,
    clientId: 3,
    clientName: 'Maria Santos',
    lastSessionDate: '2024-03-18',
    followUpDate: '2024-04-01',
    priority: 'high',
    counselor: 'Dr. Jose Reyes',
    concern: 'Career Assessment Follow-up',
  },
  {
    id: 3,
    clientId: 5,
    clientName: 'Ana Garcia',
    lastSessionDate: '2024-03-10',
    followUpDate: '2024-03-24',
    priority: 'medium',
    counselor: 'Dr. Ana Mendoza',
    concern: 'Anxiety Management',
  },
]

export const liveStatsToday = {
  todayAppointments: 8,
  activeSessions: 3,
  pendingInquiries: 5,
  emergencyCalls: 2,
}