export const users = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@therapath.com',
    password: 'admin123',
    role: 'admin',
    phone: '555-0100',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'John Doe',
    email: 'john@example.com',
    password: 'user123',
    role: 'user',
    phone: '555-0101',
    address: '123 Main St, City',
    dateOfBirth: '1995-05-15',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 3,
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'user123',
    role: 'user',
    phone: '555-0102',
    address: '456 Oak Ave, Town',
    dateOfBirth: '1998-08-22',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 4,
    name: 'Michael Johnson',
    email: 'michael@example.com',
    password: 'user123',
    role: 'user',
    phone: '555-0103',
    address: '789 Pine Rd, Village',
    dateOfBirth: '1992-11-30',
    createdAt: '2024-02-10T00:00:00Z',
  },
]

export const appointments = [
  {
    id: 1,
    userId: 2,
    userName: 'John Doe',
    userEmail: 'john@example.com',
    userPhone: '555-0101',
    date: '2024-03-25',
    time: '10:00 AM',
    type: 'Academic Counseling',
    status: 'confirmed',
    notes: 'Need guidance on course selection for next semester',
    isAnonymous: false,
    createdAt: '2024-03-15T10:30:00Z',
  },
  {
    id: 2,
    userId: 3,
    userName: 'Jane Smith',
    userEmail: 'jane@example.com',
    userPhone: '555-0102',
    date: '2024-03-26',
    time: '02:00 PM',
    type: 'Career Counseling',
    status: 'pending',
    notes: 'Exploring career options after graduation',
    isAnonymous: false,
    createdAt: '2024-03-16T14:20:00Z',
  },
  {
    id: 3,
    userId: null,
    userName: 'Anonymous',
    userEmail: 'anonymous@therapath.com',
    userPhone: 'N/A',
    date: '2024-03-27',
    time: '11:00 AM',
    type: 'Personal Counseling',
    status: 'confirmed',
    notes: 'Prefer to remain anonymous',
    isAnonymous: true,
    createdAt: '2024-03-17T09:15:00Z',
  },
  {
    id: 4,
    userId: 4,
    userName: 'Michael Johnson',
    userEmail: 'michael@example.com',
    userPhone: '555-0103',
    date: '2024-03-28',
    time: '03:00 PM',
    type: 'Academic Counseling',
    status: 'completed',
    notes: 'Follow-up on previous session',
    isAnonymous: false,
    createdAt: '2024-03-10T11:45:00Z',
  },
  {
    id: 5,
    userId: 2,
    userName: 'John Doe',
    userEmail: 'john@example.com',
    userPhone: '555-0101',
    date: '2024-03-29',
    time: '09:00 AM',
    type: 'Career Counseling',
    status: 'cancelled',
    notes: 'Had to reschedule due to conflict',
    isAnonymous: false,
    createdAt: '2024-03-18T16:30:00Z',
  },
]

export const timeSlots = [
  '09:00 AM',
  '10:00 AM',
  '11:00 AM',
  '01:00 PM',
  '02:00 PM',
  '03:00 PM',
  '04:00 PM',
]

export const appointmentTypes = [
  'Academic Counseling',
  'Career Counseling',
  'Personal Counseling',
  'Group Counseling',
  'Crisis Intervention',
]

export const clientRecords = [
  {
    id: 1,
    clientId: 2,
    clientName: 'John Doe',
    sessionDate: '2024-03-20',
    sessionType: 'Academic Counseling',
    duration: '45 minutes',
    counselor: 'Dr. Sarah Williams',
    notes: 'Student is struggling with time management. Discussed strategies for prioritizing tasks and creating a study schedule. Recommended follow-up in 2 weeks.',
    followUpRequired: true,
    followUpDate: '2024-04-03',
    status: 'active',
    createdAt: '2024-03-20T10:45:00Z',
  },
  {
    id: 2,
    clientId: 3,
    clientName: 'Jane Smith',
    sessionDate: '2024-03-18',
    sessionType: 'Career Counseling',
    duration: '60 minutes',
    counselor: 'Dr. Michael Chen',
    notes: 'Explored career interests and aptitudes. Administered career assessment test. Student shows strong interest in healthcare field. Discussed various career paths in medicine and allied health.',
    followUpRequired: true,
    followUpDate: '2024-04-01',
    status: 'active',
    createdAt: '2024-03-18T14:30:00Z',
  },
  {
    id: 3,
    clientId: 4,
    clientName: 'Michael Johnson',
    sessionDate: '2024-03-15',
    sessionType: 'Personal Counseling',
    duration: '50 minutes',
    counselor: 'Dr. Emily Rodriguez',
    notes: 'Client discussed stress management techniques. Experiencing anxiety related to academic performance. Taught breathing exercises and mindfulness practices. Progress noted from previous session.',
    followUpRequired: false,
    followUpDate: null,
    status: 'completed',
    createdAt: '2024-03-15T11:20:00Z',
  },
  {
    id: 4,
    clientId: 2,
    clientName: 'John Doe',
    sessionDate: '2024-02-28',
    sessionType: 'Academic Counseling',
    duration: '45 minutes',
    counselor: 'Dr. Sarah Williams',
    notes: 'Initial consultation regarding course selection. Reviewed academic goals and degree requirements. Provided guidance on elective choices aligned with career interests.',
    followUpRequired: true,
    followUpDate: '2024-03-20',
    status: 'completed',
    createdAt: '2024-02-28T10:15:00Z',
  },
]

export const announcements = [
  {
    id: 1,
    title: 'New Counseling Hours',
    content: 'Starting next week, we will be extending our counseling hours. We will now be available Monday through Friday from 8:00 AM to 6:00 PM, and Saturdays from 9:00 AM to 2:00 PM.',
    category: 'Schedule',
    priority: 'high',
    isActive: true,
    createdBy: 'Admin User',
    createdAt: '2024-03-20T09:00:00Z',
    expiresAt: '2024-04-20T09:00:00Z',
  },
  {
    id: 2,
    title: 'Mental Health Awareness Week',
    content: 'Join us for Mental Health Awareness Week from April 1-5. We will be hosting workshops, seminars, and group counseling sessions. All students are encouraged to participate.',
    category: 'Event',
    priority: 'high',
    isActive: true,
    createdBy: 'Admin User',
    createdAt: '2024-03-18T14:30:00Z',
    expiresAt: '2024-04-05T23:59:00Z',
  },
  {
    id: 3,
    title: 'Career Fair Preparation Sessions',
    content: 'Free career counseling sessions available for students preparing for the upcoming career fair. Learn how to create an impressive resume, practice interview skills, and network effectively.',
    category: 'Career',
    priority: 'medium',
    isActive: true,
    createdBy: 'Admin User',
    createdAt: '2024-03-15T11:00:00Z',
    expiresAt: '2024-04-15T23:59:00Z',
  },
  {
    id: 4,
    title: 'Anonymous Counseling Service',
    content: 'We now offer anonymous counseling appointments for students who prefer confidentiality. You can book appointments without providing personal information.',
    category: 'Service',
    priority: 'medium',
    isActive: true,
    createdBy: 'Admin User',
    createdAt: '2024-03-10T10:00:00Z',
    expiresAt: '2024-12-31T23:59:00Z',
  },
  {
    id: 5,
    title: 'Holiday Closure Notice',
    content: 'The counseling center will be closed on March 30th for the holiday. Emergency services will still be available through our hotline.',
    category: 'Schedule',
    priority: 'low',
    isActive: false,
    createdBy: 'Admin User',
    createdAt: '2024-03-01T09:00:00Z',
    expiresAt: '2024-03-30T23:59:00Z',
  },
]

export const inquiries = [
  {
    id: 1,
    name: 'Sarah Anderson',
    email: 'sarah@example.com',
    phone: '555-0200',
    subject: 'Group Counseling Sessions',
    message: 'I would like to know more about the group counseling sessions. What topics are covered and how can I join?',
    status: 'pending',
    createdAt: '2024-03-19T15:30:00Z',
  },
  {
    id: 2,
    name: 'David Martinez',
    email: 'david@example.com',
    phone: '555-0201',
    subject: 'Career Assessment',
    message: 'Can I schedule a career assessment test? I am unsure about my career path and need professional guidance.',
    status: 'responded',
    response: 'Thank you for your inquiry. You can schedule a career assessment through our booking system. Please select "Career Counseling" as the appointment type.',
    respondedAt: '2024-03-19T16:45:00Z',
    createdAt: '2024-03-19T14:20:00Z',
  },
  {
    id: 3,
    name: 'Anonymous',
    email: 'anonymous@example.com',
    phone: 'N/A',
    subject: 'Confidentiality Question',
    message: 'How confidential are the counseling sessions? Will my information be shared with anyone?',
    status: 'pending',
    createdAt: '2024-03-20T10:15:00Z',
  },
]

export const dashboardStats = {
  user: {
    totalAppointments: 3,
    upcomingAppointments: 2,
    completedSessions: 1,
    pendingRequests: 1,
  },
  admin: {
    totalAppointments: 5,
    pendingAppointments: 1,
    confirmedAppointments: 2,
    completedAppointments: 1,
    totalClients: 4,
    activeRecords: 3,
    totalInquiries: 3,
    pendingInquiries: 2,
  },
}

export const appointmentChartData = [
  { month: 'Jan', appointments: 12 },
  { month: 'Feb', appointments: 19 },
  { month: 'Mar', appointments: 15 },
  { month: 'Apr', appointments: 22 },
  { month: 'May', appointments: 18 },
  { month: 'Jun', appointments: 25 },
]

export const appointmentTypeData = [
  { name: 'Academic', value: 35 },
  { name: 'Career', value: 28 },
  { name: 'Personal', value: 22 },
  { name: 'Group', value: 10 },
  { name: 'Crisis', value: 5 },
]